// ── OKLCH Palette Demo ───────────────────────────────────────────────────────
// Pick a hue and see a full tint-to-shade ramp generated by walking OKLCH L.
// Because Lightness is perceptual, each step looks evenly spaced.
// Contrast badges show WCAG 4.5:1 pass/fail against white and black.

// Relative luminance (for WCAG contrast)
function srgbL(c) {
  const v = c / 255;
  return v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
}
function relLum(r, g, b) {
  return 0.2126 * srgbL(r) + 0.7152 * srgbL(g) + 0.0722 * srgbL(b);
}
function contrast(L1, L2) {
  const [lo, hi] = L1 < L2 ? [L1, L2] : [L2, L1];
  return (hi + 0.05) / (lo + 0.05);
}

// Crude oklch() → approximate sRGB for luminance (good enough for badges)
// Uses browser to resolve the colour via a hidden element
let _probe = null;
function probeRgb(cssColor) {
  if (!_probe) {
    _probe = document.createElement('div');
    _probe.style.cssText = 'position:fixed;opacity:0;pointer-events:none;width:1px;height:1px;';
    document.body.appendChild(_probe);
  }
  _probe.style.backgroundColor = cssColor;
  const s = getComputedStyle(_probe).backgroundColor;
  const m = s.match(/\d+(\.\d+)?/g);
  return m ? [+m[0], +m[1], +m[2]] : [0, 0, 0];
}

const STEPS  = 9;
const CHROMA = 0.16;
const L_STEPS = Array.from({ length: STEPS }, (_, i) => 0.12 + (i / (STEPS - 1)) * (0.95 - 0.12));

export function mount(container) {
  let hue = 240;

  container.innerHTML = `
    <style>
      .pal-wrap {
        position: absolute; inset: 0;
        background: #111;
        display: flex; flex-direction: column;
        align-items: center; justify-content: center;
        gap: 1.6rem;
        padding: 1.5rem 2rem;
        font-family: 'Silkscreen', monospace;
      }
      .pal-ramp {
        display: flex; gap: 4px;
        width: min(680px, 95vw);
      }
      .pal-step {
        flex: 1; border-radius: 4px;
        display: flex; flex-direction: column;
        align-items: center; justify-content: space-between;
        padding: 0.5rem 0;
        min-height: 100px;
        transition: background-color 0.25s ease;
      }
      .pal-step-l {
        font-size: 0.38rem; letter-spacing: 0.06em;
        text-transform: uppercase; opacity: 0.5;
      }
      .pal-step-badges {
        display: flex; flex-direction: column; gap: 2px;
        align-items: center;
      }
      .pal-badge {
        font-size: 0.3rem; letter-spacing: 0.06em;
        text-transform: uppercase;
        padding: 1px 4px; border-radius: 1px;
      }
      .pal-badge.pass { background: rgba(0,200,80,0.25); color: rgba(80,255,140,0.9); }
      .pal-badge.fail { background: rgba(200,0,0,0.18);  color: rgba(255,80,80,0.7);  }
      .pal-hue-row {
        display: flex; align-items: center; gap: 1rem;
        width: min(520px, 90vw);
      }
      .pal-hue-label {
        font-size: 0.5rem; letter-spacing: 0.1em;
        text-transform: uppercase;
        color: rgba(255,255,255,0.4);
        width: 6rem; flex-shrink: 0;
      }
      .pal-hue-row input[type=range] {
        flex: 1; height: 2rem; cursor: pointer; accent-color: white;
      }
      .pal-caption {
        font-size: 0.5rem; letter-spacing: 0.08em;
        text-transform: uppercase;
        color: rgba(255,255,255,0.3); text-align: center;
        max-width: 500px; line-height: 1.7;
      }
    </style>
    <div class="pal-wrap">
      <div class="pal-ramp" id="pal-ramp"></div>
      <div class="pal-hue-row">
        <span class="pal-hue-label" id="pal-hue-lbl">Hue: ${hue}°</span>
        <input type="range" id="pal-hue" min="0" max="360" value="${hue}" aria-label="Hue">
      </div>
      <span class="pal-caption">
        WCAG badges show 4.5:1 contrast against white (W) and black (K).
        OKLCH steps are perceptually even — any brand colour, one formula.
      </span>
    </div>
  `;

  const ramp = container.querySelector('#pal-ramp');

  // Build step elements
  const steps = Array.from({ length: STEPS }, () => {
    const el = document.createElement('div');
    el.className = 'pal-step';
    const lbl = document.createElement('span');
    lbl.className = 'pal-step-l';
    const badges = document.createElement('div');
    badges.className = 'pal-step-badges';
    el.appendChild(lbl);
    el.appendChild(badges);
    ramp.appendChild(el);
    return { el, lbl, badges };
  });

  const hueLbl = container.querySelector('#pal-hue-lbl');

  function render() {
    hueLbl.textContent = `Hue: ${hue}°`;

    steps.forEach(({ el, lbl, badges }, i) => {
      const L = L_STEPS[i];
      const col = `oklch(${L.toFixed(2)} ${CHROMA} ${hue})`;
      el.style.backgroundColor = col;

      lbl.textContent = `L=${L.toFixed(2)}`;

      // Contrast badges
      const [r, g, b] = probeRgb(col);
      const cLum = relLum(r, g, b);
      const cW = contrast(cLum, 1.0);   // vs white
      const cK = contrast(cLum, 0.0);   // vs black
      badges.innerHTML = `
        <span class="pal-badge ${cW >= 4.5 ? 'pass' : 'fail'}">W ${cW.toFixed(1)}</span>
        <span class="pal-badge ${cK >= 4.5 ? 'pass' : 'fail'}">K ${cK.toFixed(1)}</span>
      `;
    });
  }

  container.querySelector('#pal-hue').addEventListener('input', e => {
    hue = +e.target.value; render();
  });

  render();
  return () => {
    if (_probe) { _probe.remove(); _probe = null; }
    container.innerHTML = '';
  };
}
